name: asv

on:
  workflow_dispatch:
  # schedule:
  #   - cron: 0 4 * * *

jobs:
  asv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: astral-sh/setup-uv@v3
      - name: Set up Python 3.12
        run: uv python install 3.12


      - name: Run the ASV benchmarks
        run: |
          make .venv
          make asv-machine
          make asv
