name: asv

on:
  workflow_dispatch:
  # schedule:
  #   - cron: 0 4 * * *

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  asv:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: astral-sh/setup-uv@v3
        with:
            enable-cache: true
            cache-dependency-glob: "uv.lock"
      - name: Set up Python 3.12
        run: uv python install 3.12
      - name: Install the project
        run: make install

      - name: Fingerprint the machine
        run: |
          uv run asv machine --yes \
            --machine github-action \
            --os `uname -srm` \
            --cpu `lscpu | grep 'Model name' | cut -f 2 -d ":" | awk '{$1=$1}1'` \
            --num_cpu `nproc --all` \
            --ram `grep MemTotal /proc/meminfo | awk '{print $2}'`
      - name: Run the ASV benchmarks
        run: make asv
      - name: Generate the ASV website
        run: make html

      - name: Commit the generated benchmark results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add CI benchmark runs"

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .asv/html/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
